import type { NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const { data } = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const { data: session, status } = useSession();

  console.log(status);
  return (
    <>
      <Head>
        <title>Card deck shuffler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>

      <main className="container flex flex-col items-center justify-center h-screen p-4">
        <div>test</div>
      </main>
    </>
  );
};

export default Home;
